### ISSUE TITLE
Handle database schema upgrade from v11 to v16

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#1]
This is a the most involved change of the conversion. 
It will be difficult to perform this in an all-or-nothing fashion because it will impact most aspects of `libAnki` in some manner

General Idea:

* Upgrade `anki` submodule to a stable version (current commit is buggy: https://github.com/ankitects/anki/pull/766)
* Determine data persistence functionality required for schema upgrade
   * Port each behind a backwards-compatible interface if possible 
* Determine where database should be downgraded to Schema 11

Current schema version is defined in:

https://github.com/ankitects/anki/blob/af911aa66992d08278b4bca61be7e4ae5ce7c3fa/rslib/src/storage/upgrades/mod.rs

**Comment by david-allison-1** [comment]
I'll upgrade to 2.1.34 before releasing the library. This will allow a "downgrade & quit" in 2.15 to work with the latest version of Anki

https://github.com/ankitects/anki/commit/87c6686930999d01a43bcaea563d8a625ceb53cc was the latest schema change which was live.

https://github.com/ankitects/anki/commit/b276ce3dd508e859ca88bb3ae870548ccb936dd6 upgrades to v17, but this is not yet released.

**Comment by dae** [comment]
Can be closed? The remaining work is not in this repo.

**Comment by mikehardy** [comment]
Agreed - even if there is work in the repo I think the work frontier has moved past this long ago! A good thing
