### ISSUE TITLE
Audit: AnkiDatabaseCursor

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#103]
I mistakenly thought that this was internal to AnkiDroid, instead its API surface is provided to consumers by our `ContentProvider` API.

Some of the methods were not implemented because they were not needed for AnkiDroid, and these will need to be checked

**Comment by david-allison-1** [comment]
@mikehardy We'll need to look into our test architecture after this, there seems to be subtle differences between a real project using our API, and running via `androidTest` on the emulator.

I'm fairly sure it'll be the calls to `moveToPosition/move()`, which I'm sorting currently.

**Comment by mikehardy** [comment]
Given androidTest is on emulator, I believe the differences would be detected if we actually went through the API (where apparently things are wrapped one more time?) vs testing via more internal APIs. The API is exercised already in other areas but maybe just not this particular one?

**Comment by david-allison-1** [comment]
> Given androidTest is on emulator, I believe the differences would be detected if we actually went through the API (where apparently things are wrapped one more time?) vs testing via more internal APIs. The API is exercised already in other areas but maybe just not this particular one?

I'll need to look into it further after we have more slack time: the provided repro case in the Pleco issue passed while running under `androidTest`: 

This could possibly be because we're running using instrumentation, rather than a real use of the API.

**Comment by mikehardy** [comment]
Could be, I'd be surprised given what I know about how instrumentation works via some deep dives into testing frameworks and coverage integration just recently for react-native-firebase + Detox + JaCoCo but software fails in infinite ways. My hunch is that the current tests just aren't full integration tests somehow and are exercising layers with one ore more fewer layers of indirection by (naively incorrect but seemed fine until now) design, vs something instrumentation-specific

**Comment by david-allison-1** [comment]
OK, just for reference: we'll need tests which exercise:

`android.database.CursorToBulkCursorAdaptor`

`DatabaseUtils.cursorFillWindow`

**Comment by dae** [comment]
If you don't feel you'll get to this any time soon, maybe we should close it?
