### ISSUE TITLE
[CI] Perf: Unpin old Python Version

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#106]
for discussion: We can likely remove the need for an older version of Python now we're on the latest version of `protobuf-compiler`

If we're using (and checking) the native version of Python for the machine, this should save a few minutes.

**Comment by dae** [comment]
I don't see any pins - can this be closed?

**Comment by mikehardy** [comment]
A quick glance reveals this for me?

https://github.com/ankidroid/Anki-Android-Backend/blob/eeb5b2917ec5006feebc2187d6afa364c120bdc1/.github/scripts/linux_install_protobuf.sh#L8-L12

https://github.com/ankidroid/Anki-Android-Backend/blob/eeb5b2917ec5006feebc2187d6afa364c120bdc1/.github/scripts/macos_install_protobuf_compiler.sh#L20-L23

I have not inspected deeply but those appear to be old versions.
No idea why a) we need older versions or b) we're doing this in semi-opaque sub-scripts vs using a setup-python action and just including the needed logic in a workflow step (I generally don't like sub-scripts in CI if they can be avoided...)
