### ISSUE TITLE
Provide sources for protobuf-generated files in Build Directory

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#15]
In particular: `RustBackend` is auto-generated and documentation is vital in understanding the parameters.

We currently see a decompilation:

```java
UInt32 findAndReplace(List<Long> var1, @Nullable String var2, @Nullable String var3, boolean var4, boolean var5, @Nullable String var6);
```

whereas we should see:

```java
Backend.UInt32 findAndReplace(List<Long> nids, @Nullable String search, @Nullable String replacement, boolean regex, boolean matchCase, @Nullable String fieldName);
```

Note: The decompilation is seen when the library is obtained from `files()` - confirm if this is the same if obtained from Maven

**Comment by david-allison-1** [comment]
Sources are included in the maven upload, but this does not (yet) include files in the build directory.

**Comment by dae** [comment]
This appears to have been fixed somewhere along the way? The backend methods show proper parameter names when hovering over them for me, at least when testing locally in the AnkiDroid project.

**Comment by mikehardy** [comment]
is that still true when using the maven artifact and zero file references (and ...just thinking of how to really test the consumer experience in AnkiDroid) after invalidate caches + restart ?

**Comment by dae** [comment]
Seems to be - AnkiDroid main branch, invalidate caches, and the argument names show up correctly on hover or when jumping to the declaration (which shows the decompiled class file):

```

    DeckID addOrUpdateDeckLegacy(@Nullable ByteString deck, boolean preserveUsnAndMtime);

    DeckTreeNode deckTree(long now, long topDeckId);

```

**Comment by mikehardy** [comment]
sounds fantastic - thanks!
