### ISSUE TITLE
Alter publish to avoid using David personal sonatype account

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#162]
Note: The publishing should be moved away from `david-allison-1` at some point in the future.

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android-Backend/issues/32#issuecomment-1050215381_

https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/.github/workflows/publish_library.yml#L39-L46

**Comment by david-allison** [comment]
Duplicate of #33

**Comment by mikehardy** [comment]
Oh darn
