### ISSUE TITLE
AnkiDroid unit test suite currently not working on arm64 JDKs on macOS

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#164]
**[UPDATE: until solved, we publish `rsdroid-arm64.dylib` on each release in the list of the artifacts and you can point the robolectric tests to it for use on M1 machines]**

----

Symptom:

```
    java.lang.UnsatisfiedLinkError: /private/var/folders/5b/1q9_lqrs79ng7n9hjm_xl4cm0000gn/T/librsdroid2032698931526253765.dylib: dlopen(/private/var/folders/5b/1q9_lqrs79ng7n9hjm_xl4cm0000gn/T/librsdroid2032698931526253765.dylib, 0x0001): tried: '/private/var/folders/5b/1q9_lqrs79ng7n9hjm_xl4cm0000gn/T/librsdroid2032698931526253765.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librsdroid2032698931526253765.dylib' (no such file)
```

@viciousAegis This is a bug on our side. We do not build `io.github.david-allison-1:anki-android-backend-testing` for M1 Macs.
 
I have an M1 Mac arriving sometime late March, so I'll be personally invested in testing

As a workaround: 
* Remove `@RunWith(AndroidJUnit4::class)`
* Remove `:RobolectricTest()`
* This will only work because the test does not depend on the Anki Database

As a workaround, please enable GitHub actions on your GitHub clone of `Anki-Android` and test there

## Properly fixing this

**Issue**  
* We have a library written in rust: `librsdroid`. This is compiled for Android
* Robolectric doesn't run Android, it runs tests via the JVM on your PC
* Therefore, `librsdroid` needs to be compiled for native platforms
* We have a separate library: `anki-android-backend-testing` which contains the `dlls` and `dylibs` needed
* When this was written, M1 macs didn't exist

Please see: https://github.com/ankidroid/Anki-Android-Backend/tree/main/rsdroid-testing

* First of all, this isn't well documented. Please submit a PR with better documentation if you want
* Most of the work is performed via GitHub actions
* Feel free to submit a pull request to the GitHub actions get this working. 
  * Compile the dylib for `arm64e` (I have no idea how to do this, but it should be possible)
    * The code should be: https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/rsdroid-testing/build.gradle#L184-L202
  * Include two `dylibs` in the `jar`
  * Fix this code to select the correct `dylib` based on your architecture:
    * https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/rsdroid-testing/src/main/java/net/ankiweb/rsdroid/testing/RustBackendLoader.java#L55-L64

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10389#issuecomment-1052602567_

**Comment by david-allison** [comment]
Also:

> We should be able to cross-compile Rust for `arm64e`. This /should/ be doable by adding  `aarch64-apple-darwin` in:
> 
> https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/rsdroid-testing/build.gradle#L109-L114
> 
> and installing the target platform: https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/.github/scripts/install_rust_robolectric_targets.sh
> 
> And then:
> 
> * An option in the .java to detect an M1 and pull the correct dylib
> * A fix to to [check_robolectric_assets.sh](https://github.com/ankidroid/Anki-Android-Backend/blob/9302b3f89e09643e95c42166743f8563a3822ddc/.github/scripts/check_robolectric_assets.sh) allow 2 dylibs in the `.jar`
> 
> Note that `aarch64-apple-darwin` is a [Tier 2 target](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools) in Rust.

https://github.com/ankidroid/Anki-Android/pull/10389#issuecomment-1052917130

**Comment by david-allison** [comment]
Got this working.

But: `cross` doesn't support `aarch64-apple-darwin` yet: https://github.com/cross-rs/cross/issues/508, so we won't be able to build a `dylib` in CI.

I'm open to suggestions, but for now, I'll build a dylib for arm64 and will include it in the releases folder, along with a PR in `Anki-Android` to get an override working via environment variable 

Before this PR: replace 

https://github.com/ankidroid/Anki-Android/blob/f0aa92f54dec9475fe23e18c980fb3fe735bcff1/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt#L92

with a call to load the dylib

`        RustBackendLoader.loadRsdroid("/Users/davidallison/StudioProjects/Anki-Android-Backend/rslib-bridge/target/aarch64-apple-darwin/release/librsdroid.dylib")
`

**Comment by mikehardy** [comment]
osxcross supports arm64e now, so this triple (aarch64-apple-darwin) is probably supportable 
https://github.com/multiarch/crossbuild/issues/51#issuecomment-1004960611

This is the PR for x86_64-apple-darwin support to cross-r/cross: https://github.com/cross-rs/cross/pull/480
I imagine something based on that would build a Docker image that could then be used with cross-rs/cross via an image tag for the triple

**Comment by mikehardy** [comment]
I want to leave this open for a bit. I just generated the 0.1.11 artifact and here was how I did it:

```bash
git co 0.1.11
git submodule update --recursive
./tools/doctor.sh  # this sets the correct rust version etc, installs targets or should etc
rustup target add aarch64-apple-darwin
cd rslib-bridge
cross build --release --features no-android --verbose --target aarch64-apple-darwin
open target/aarch64-apple-darwin/release/  # now you have a finder window open with rsdroid.dylib there
```

Open up the tag here on the releases page https://github.com/ankidroid/Anki-Android-Backend/releases
Edit the release
Drop rsdroid.dylib on there

How exactly to integrate it after merging #202 is up in the air - I have not tested - but this should be updated once tested
