### ISSUE TITLE
Use doctor more in environment doc, and use tools/scripts more in doctor

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#174]
Also, it appears that there is duplication between these files and doctor and the .github/scripts, where this could point to doctor more, and doctor could use the .github/scripts more

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android-Backend/issues/173#issuecomment-1092380334_

**Comment by dae** [comment]
There's not a lot that needs to be manually installed now - do you still feel this needs addressing?

**Comment by mikehardy** [comment]
No - I think the docs right now are pretty good. After my windows laptop blew up just a week or whatever back I had to clean install, and I also built a new macos machine recently - so I just had fresh eyes on the "clone repo and follow docs" process, it was all pretty simple.
