### ISSUE TITLE
Update NDK / native build tools to latest version

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#179]
Right now we're not just using an obsolete / unsupported version (r22) we're using the 22.0 version of it while r22b is out.

But we should move to the latest stable release https://github.com/android/ndk/wiki#current-stable-release

Right now that is r24 / 24.0.8215888

This is useful as part of a general strategy to get everything updated so native M1 builds work as well...
https://github.com/android/ndk/issues/1299#issuecomment-1026338583

That comment lists these things plus some config to do to use correct cmake version

- [x] Android Studio 2021.1.1
- [x] Android Gradle Plugin 7.1.0 (the plugin includes an aapt2 binary)
- [x] Android SDK Build-Tools 32.1-rc1 (SDK's stable channel)
- [x] Android SDK Platform Tools 32.0.0 (SDK's stable channel)
- [x] Android NDK 24.0.8215888
- [x] CMake 3.22.1 (SDK's canary channel)
```

**Comment by dae** [comment]
Is anything remaining here?

**Comment by mikehardy** [comment]
No, I'm going to open a separate issue to bump the compile / target sdk versions but you nailed getting the NDK and toolchain stuff up to date, so M1 native builds should be great now after the #294 epic
