### ISSUE TITLE
Backend fails to load large collection with VNext due to missing /tmp

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android-Backend#193]
When testing with a moderately large collection, the collection fails to open when VNext is enabled. A fix is available upstream (https://github.com/ankitects/anki/commit/f15e294981bb7bfda8aad0136cc7b82d724a2467); recommend you cherry-pick it into the @david-allison/2.1.34 fork. Might also be worth moving it to this organization?

**Comment by mikehardy** [comment]
0- thanks for testing it!
1- Definitely want everything in the ankidroid org if at all possible, as we have a crew here (including David) with permissions delegated vs a one-person org/repo
2- I had a question on the patch, left in comment there
3- once question is resolved and fork is here, +1 for cherry-pick, I can't think of another way to manage necessary patches like that

**Comment by dae** [comment]
I was still seeing that error when trying to import a large colpkg; switching to a file approach appears to have solved it:

https://github.com/ankidroid/Anki-Android/pull/11600
