### ISSUE TITLE
Update OVERVIEW / diagrams to match new backend state

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#209]
> Before I spend much more time on this, I'd appreciate it if you could let me know whether you're amenable to the changes in [b02515b](https://github.com/ankidroid/Anki-Android/commit/b02515b0f6a403a4e9f278d21620a1b07d0b1232). I was planning to build upon them to look into adding some new backend functionality, and don't really relish the thought of having to add all the extra boilerplate to do so.

I am personally okay with it, in the first instance by criteria of "implementor's choice" but also by scanning the overview doc and reasoning about the initial motivation:

https://github.com/ankidroid/Anki-Android-Backend/blob/main/docs/OVERVIEW.md#droidbackendrustdroidbackend

> Allows a testable comparison between the Java and the Rust during the conversion

I think this was useful but may have served it's purpose. We're definitely going to use rslib. The babel's tower of build toolchains and languages in use is a bit baroque, but we're using it live, we're not going back. How much value does a comparison with a java implementation that's never going to keep up with rslib development have? My opinion, none in future

> Allows a pure Java conversion afterwards (if deemed appropriate due to AGPL concerns)

I don't think we have those concerns? I do not have those concerns

> Encapsulates all access to the Rust, allowing the implementation to later be swapped out within one file.

Similar to first statement above: swapped out with what? I don't intend to get into an Anki development competition with rslib development so there will never be a full-featured swapout

https://github.com/ankidroid/Anki-Android-Backend/blob/main/docs/OVERVIEW.md#rustbackend-interface

One point here is interesting:

> Allows for easy mocking, and method discovery

Is easy mocking for testability interesting? Is this even the appropriate layer for testing the code - that is who would be mocking out RustBackend, is it a facility actually used now, and would any change proposed here alter that? I don't have a feel for it

In general, if this goes ahead it would be good to update the docs / diagrams for future intrepid explorers: 

> Source: docs/sources/sequence_method_call.plantuml. Created with [planttext](https://www.planttext.com/)

I personally don't see a problem. We're going to use rslib, no way around it. We either commit (which again: is not user hostile, I just scanned exception reports again) or are in a dev race with rslib which is a non-starter. The interfaces are code-gen'd so just calling in as simply as possible seems right to me.

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/11644#issuecomment-1159485319_

**Comment by dae** [comment]
Done apart from the diagrams: https://github.com/ankidroid/Anki-Android-Backend/pull/202/commits/a11136529c1d0e63930696d3434a2ef83b07b137

**Comment by mikehardy** [comment]
I'm okay with that and on a read it has the whole blueprint captured, works for me - thank you!

**Comment by mikehardy** [comment]
:thinking: `./test-current.sh` has some worrying output, one seems to indicate there will  be a race condition in which proto file is in output but I am not familiar with the list of proto input files?

```
> Task :rsdroid:extractIncludeDebugUnitTestProto UP-TO-DATE
proto file '/home/mike/work/AnkiDroid/Anki-Android-Backend/rslib-bridge/anki/proto/anki/notetypes.proto' directly specified in configuration. It's likely you specified files('path/to/foo.proto') or fileTree('path/to/directory') in protobuf or compile configuration. This makes you vulnerable to https://github.com/google/protobuf-gradle-plugin/issues/248. Please use files('path/to/directory') instead.

> Task :rsdroid:extractIncludeReleaseUnitTestProto UP-TO-DATE
proto file '/home/mike/work/AnkiDroid/Anki-Android-Backend/rslib-bridge/anki/proto/anki/notetypes.proto' directly specified in configuration. It's likely you specified files('path/to/foo.proto') or fileTree('path/to/directory') in protobuf or compile configuration. This makes you vulnerable to https://github.com/google/protobuf-gradle-plugin/issues/248. Please use files('path/to/directory') instead.
```

The second part is that there is a successful build but the instrumentation run actually fails, at least for me on Ubuntu22 with API31 emulator running:

```
BUILD SUCCESSFUL in 5s
104 actionable tasks: 5 executed, 99 up-to-date
android.util.AndroidException: INSTRUMENTATION_FAILED: net.ankiweb.rsdroid.instrumented.test/androidx.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:524)
	at com.android.commands.am.Am.runInstrument(Am.java:199)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{net.ankiweb.rsdroid.instrumented.test/androidx.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:62)
	at com.android.commands.am.Am.main(Am.java:50)
INSTRUMENTATION_STATUS_CODE: -1
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

If I change `test-current.sh` to drop the final line and use target connectedAndroidTest like so it runs things for me though:

```
NO_CROSS=true CURRENT_ONLY=true ./gradlew rsdroid:test rsdroid-instrumented:connectedAndroidTest
```

**Comment by mikehardy** [comment]
doctor needs this so we have stringcase which is I think new?

```diff
diff --git a/tools/doctor.sh b/tools/doctor.sh
index 6ffc61a..dd1e0fb 100755
--- a/tools/doctor.sh
+++ b/tools/doctor.sh
@@ -85,9 +85,9 @@ else
   error_echo "Protobuf compiler (protoc) is not found"
 fi
 
-if [[ $(pip3 install protobuf) ]]; then
-  ok_echo "Protobuf python library is installed"
+if [[ $(pip3 install stringcase) ]]; then
+  ok_echo "Stringcase python library is installed"
 else
     echo -e "Try installing with python 3.7"
-    error_echo "Failed installing Protobuf python libraries"
+    error_echo "Failed installing Stringcase python libraries"
 fi
\ No newline at end of file
```

**Comment by dae** [comment]
I think those proto warnings existed before the PR too. From what I can tell, it shouldn't be an issue unless we have two proto files with the same name in different folders, which we don't.

Have fixed doctor + test-current

**Comment by mikehardy** [comment]
> Have fixed doctor + test-current

Thanks! Sorry these comments were sprinkled over here - poor review cohesion on my part. hidden here as resolved
