### ISSUE TITLE
chore: Build sqlite.proto in Anki-Android-Backend

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#21]
This removes an AnkiDroid-specific feature from  `/anki`, which moves it closer to upstream and means we don't need to rebuild the library when making an AnkiDroid specific change.

* Add protobuf generation code into `rslib-bridge/build.rs`
* Enable building Java-based protobufs from Anki-Android-Backend

**Comment by david-allison-1** [comment]
https://github.com/david-allison-1/anki/commit/8a0820672e55831921b6ae9114bad759274dc214

https://github.com/david-allison-1/anki/commit/ad1f9c986609ae0e6efce9246a250c14c67c0a63

DBResponse can be moved entirely to AnkiDroid

**Comment by david-allison-1** [comment]
Required for https://github.com/ankidroid/Anki-Android/issues/5805

Our underlying Anki implementation is past schema 14, which stored config in a separate table.

We need to define a legacy `sched_timing_today` which accepts a `SchedTimingTodayIn`, rather than obtaining the data from the config.

**Comment by david-allison-1** [comment]
Partially implemented, we do not currently link `backend.proto` and `AdBackend.proto` so switching a message with a dependency currently isn't handled
