### ISSUE TITLE
Doctor: ensure linker-wrapper.sh works

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#212]
https://github.com/mozilla/rust-android-gradle/blob/master/plugin/src/main/resources/com/nishtahir/linker-wrapper.sh depends on `python` by default, which is not checked for (only `python3`)

https://github.com/mozilla/rust-android-gradle/blob/e5006b5ad1374c08d6fad0d05df779caa52729b9/README.md#specifying-paths-to-sub-commands-python-cargo-and-rustc

Doctor does not check this

```
"/Users/davidallison/StudioProjects/Anki-Android-Backend/rslib-bridge/target/x86_64-linux-android/release/deps/librsdroid.so" "-shared" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /Users/davidallison/StudioProjects/Anki-Android-Backend/build/linker-wrapper/linker-wrapper.sh: line 4: python: command not found
```

**Comment by dae** [comment]
I vote to close this, as the build scripts automatically put the desktop's Python version on the path.
