### ISSUE TITLE
Have `AnkiSupportSQLiteDatabase.withFramework` accept a `DefaultDbCallback`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#214]
(minor/thoughts/another issue): Is it possible to have `AnkiSupportSQLiteDatabase.withFramework` accept a `DefaultDbCallback`, as that would be safer https://github.com/ankidroid/Anki-Android-Backend/blob/8e09b32c34ea5659581dce2764a911367f9e1706/rsdroid/src/main/java/net/ankiweb/rsdroid/database/AnkiSupportSQLiteDatabase.kt#L45

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/11644#discussion_r907919794_

**Comment by dae** [comment]
@david-allison is this worth keeping around?
