### ISSUE TITLE
rust-android-gradle: investigate parallel Rust builds

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#27]
Unsure if this is feasible, but we could potentially get a x4 speedup on aspects of the Android builds, and x3 on the macOS builds

**Comment by david-allison-1** [comment]
Pending issue 8176 on rust-android-gradle

We can likely implement `-Zmultitarget` for Robolectric Linux/Windows/macOS builds

**Comment by TarekkMA** [comment]
When compiling rust my device CPU utlilzation jumps to 100% and the fans stars kiking. So I don't know if parallizing it would increase the speed.

**Comment by mikehardy** [comment]
From #246 

> Bumps #27 (I recommend closing this; single-platform is the default for local builds, and CI runners don't have any extra compute available)

Agreed here
