### ISSUE TITLE
Maven publish gradle tasks not initialized

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#298]
Something about the PRs between the last public release (0.1.21-anki2.1.61 - visible here https://repo1.maven.org/maven2/io/github/david-allison-1/anki-android-backend/) and the current state of main after merging #294 made the maven upload tasks disappear

This command is part of the release workflow:

> ./gradlew rsdroid:uploadArchives -DtestBuildType=release -Dorg.gradle.daemon=false -Dorg.gradle.console=plain

...and if you run `./gradlew -q rsdroid:tasks --all` you won't see an `uploadArchives` task anymore

Seen in this attempt to publish here: https://github.com/ankidroid/Anki-Android-Backend/actions/runs/5953436455/job/16149270782#step:13:22

It does show up just prior to merge of #294 so I think it is the changes in the last merged PR that are causing the issue

**Comment by mikehardy** [comment]
current thinking: the maven publishing plugin we use is extraordinarily out of date (version 0.14) while version 0.25.3 is avialable (https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/CHANGELOG.md). Going to attempt to update

**Comment by mikehardy** [comment]
Some required changes from the changelog:

1. alter environment variables:

> 0.15.0 (2021-04-24)
>
> BREAKING: Removed support for deprecated RELEASE_REPOSITORY_URL, SNAPSHOT_REPOSITORY_URL, SONATYPE_NEXUS_USERNAME, SONATYPE_NEXUS_PASSWORD environment variables and properties. For safety reasons the project will fail when finding these. Use mavenCentralUsername and mavenCentralPassword Gradle properties or ORG_GRADLE_PROJECT_mavenCentralUsername and ORG_GRADLE_PROJECT_mavenCentralPassword environment variables instead.

2. change which target we call

> 0.17.0 (2021-07-04)
>
> Removed the deprecated uploadArchives and installArchives tasks. Use publish and publishToMavenLocal instead.

And it looks like 0.22.0 added the ability to close + release the repository if things are successful! https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/CHANGELOG.md#0220-2022-09-09

...going to try all of this 🤞

**Comment by mikehardy** [comment]
Really close! Got rsdroid but forgot rsdroid-testing

> Cannot locate tasks that match 'rsdroid-testing:publishAllPublicationsToMavenCentral' as task 'publishAllPublicationsToMavenCentral' not found in project ':rsdroid-testing'.

**Comment by dae** [comment]
Thanks Mike. I know it's not much fun iterating on something when the feedback cycle is two hours.

**Comment by mikehardy** [comment]
I've got 3 other contracts in progress so it's not so bad, just hit the button then check back later. Honestly pleased to be honest, I *almost* sniped this one first shot. Got really close anyway. And now the whole publish is auto, no manual steps on maven central

This repo keeps getting easier to deal with

**Comment by mikehardy** [comment]
Seemingly all published now

Next step: head to the main repo and update PR commit to stop using local_backend=true and use the new artifact

Takes an hour or three for maven central to sync so it's available though
