### ISSUE TITLE
macOS build fails using ninja (works with n2)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#311]
Hey @dae not sure whether this is worth fixing as a technical "make the build work with ninja" fix or just via documentation to say "use n2 on macOS and linux, use ninja on windows"

But if you attempt to build on macOS right now, and you have not run `anki/tools/install-n2`, then the build fails with some sort of environment variable interpolation / pathing issue where the out directory isn't right as it tries to do the protoc / typescript work

`build.sh` -->

```

   Compiling backtrace v0.3.69
   Compiling globset v0.4.13
   Compiling num_cpus v1.16.0
   Compiling lazy_static v1.4.0
   Compiling maplit v1.0.2
   Compiling snafu-derive v0.7.5
   Compiling snafu v0.7.5
   Compiling anki_io v0.0.0 (/Users/mike/work/ankidroid/Anki-Android-Backend/anki/rslib/io)
   Compiling ninja_gen v0.0.0 (/Users/mike/work/ankidroid/Anki-Android-Backend/anki/build/ninja_gen)
   Compiling configure v0.0.0 (/Users/mike/work/ankidroid/Anki-Android-Backend/anki/build/configure)
    Finished dev [unoptimized + debuginfo] target(s) in 12.79s
     Running `out/rust/debug/configure`
build:configure_bin
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
failed: build:configure
Failed to execute: /rust/debug/configure
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `out/rust/debug/configure`
failed: build:configure
Failed to execute: /rust/debug/configure

Build failed.
Error: Failed with code Some(1): ./ninja extract:protoc ts:reviewer:reviewer_extras_bundle.js qt:aqt:data:web:pages

```

**Comment by dae** [comment]
This happens when you have an old version of n2 installed. There were some changes to the build process which require running an updated n2, so install-n2 needs to be run once more.

**Comment by mikehardy** [comment]
that could be it - I'm not 100% sure this machine was "backend build pristine" before - I thought it was so that it provided a good "non-n2" build case but it's also possible this had a previous build and thus an old n2 I'll take your word for it since you're obviously closer to the bits in this area than I am. Any way to guard against this? The community of developers that could be affected is pretty low, maybe just a quick note in the README to update n2 via a re-run of the install command if you see errors. I'll probably hack something in there in a moment, mostly as a note to myself

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android-Backend/commit/d7b4c250637f21f8c6eb915b879f7a535e91a712

**Comment by dae** [comment]
You should be able to confirm by using 'cargo uninstall n2', confirming there's no n2 on the path (only ninja), and then seeing if the build works again. FWIW, I don't expect such upgrades to be required frequently.
