### ISSUE TITLE
Move library to ankidroid org

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#32]

**Comment by mikehardy** [comment]
This one is effectively trivial no? There are no outside dependencies here that I'm aware of, just some github twiddling?
In my experience these things are actually best handled by a single person with appropriate powers as there is always some little thing on each side that was not anticipated. Do you have sufficient powers in the ankidroid org on github to do this yourself ? If not let me know what specific powers are missing and I'll hit you the magical power wand

**Comment by mikehardy** [comment]
@david-allison this is one I can't do because I don't have admin rights here, but if you gave me admin on this repo I'd move it. I would like to work on the backend a bit but not until it's a repo in the ankidroid org

**Comment by david-allison** [comment]
Done: https://github.com/ankidroid/Anki-Android-Backend

Note: The publishing should be moved away from `david-allison-1` at some point in the future.
