### ISSUE TITLE
Maven publish currently failing

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#347]
Something about #346 perturbed publish so that it is failing now

No pressure since I went for a release when it was totally unnecessary for precisely this reason

```

* What went wrong:
Execution failed for task ':rsdroid:createStagingRepository'.
> A failure occurred while executing com.vanniktech.maven.publish.sonatype.CreateSonatypeRepositoryTask$CreateStagingRepository
   > Cannot get stagingProfiles for account david-allison-1: <html>
       <head>
         <title>403 - Forbidden</title>
         <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
     
         <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">
         <!--[if IE]>
         <link rel="SHORTCUT ICON" href="https://oss.sonatype.org/favicon.ico"/>
         <![endif]-->
     
         <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.15.1-02" type="text/css" media="screen" title="no title" charset="utf-8">
       </head>
       <body>
         <h1>403 - Forbidden</h1>
         <p>Forbidden</p>
       </body>
     </html>
* Try:
```

**Comment by david-allison** [comment]
I believe this could also be:

* https://github.com/ankidroid/Anki-Android-Backend/pull/342

https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/CHANGELOG.md#0270-2024-01-06

**Comment by david-allison** [comment]
We should modify CI to `git tag` versions

**Comment by mikehardy** [comment]
I like the idea of the git tag, can throw that in as I'm working on this

I agree that is the likely cause of the problem - it is actually the reason I wanted to do a test publish - I'd read the changelog and thought to myself it was likely going to break something / I need to test that when it's low pressure

For any future readers: I'm 100% okay with a revert on that one if all the sudden there *is* pressure to release, but I think we've got plenty of time to fix it (where "we" is me, I plan on getting it eventually...)

**Comment by mikehardy** [comment]
This is becoming more urgent - I have been keeping an eye on it, but the first beta of next anki release is up so this needs to be ready to go shortly https://github.com/ankitects/anki/releases/tag/24.04beta1

Note that reverts are always possible if forward-porting is time-prohibitive (that's a note to myself as much as anyone!)

**Comment by mikehardy** [comment]
I do believe it was this simple: https://github.com/ankidroid/Anki-Android-Backend/commit/bf2fdc9ce8b6b0bd44609037b44ae10c1666dd78

We already have the version bumped here but unpublished - I have to attempt a publish off main in order try it so I went ahead and did the commit then we'll see

https://github.com/vanniktech/gradle-maven-publish-plugin/issues/720

which leads to https://github.com/vanniktech/gradle-maven-publish-plugin/pull/733

which documents to use `CENTRAL_PORTAL` as the host now https://github.com/vanniktech/gradle-maven-publish-plugin/pull/733/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR6

and is in the 0.28 version I just merged

**Comment by mikehardy** [comment]
@david-allison - okay, reverting the plugin didn't work, it turns out the 0.27 release was just coincidental with a switch in how Maven Central wants things to work, and 0.28 is actually needed to handle it

Okay...so the real / fixing-it-forward fix is to adopt The New Way Of Doing Things at Maven Central.

They consider oss.sonatype.com "legacy" now, and they want everyone to switch to the "Central Portal", which has a new auth system etc.

https://github.com/vanniktech/gradle-maven-publish-plugin/issues/720 at the end has some clues

I *believe* the steps are 

- to somehow log in to the Central Portal (does the existing legacy user/pass work? it appears you can contact them to work through creating a valid auth in their new system and claiming your publishing coordinates?)
- to then generate an auth token in the new auth system
- to switch here from target `DEFAULT` to `MAVEN_CENTRAL` in the two build.gradle files while moving the publish plugin back to version 0.28, and alter the github repo secret used in publishing such that the password is your new auth token
- then re-run publishing

I don't believe I can do any of this except last steps...

**Comment by david-allison** [comment]
My access has not been transferred on Central (likely due to the username change from `david-allison-1`)

I've sent in a support ticket to claim the namespace

If this fails, the likely next step is to publish under `io.github.ankidroid` (if we can get access), or `io.github.david-allison`

**Comment by david-allison** [comment]
> Hello David,
> 
> While it is possible for us to migrate you to Central Portal, please note publishing to Central Portal and to Central's legacy NXRM (also called OSSRH) are two different methods: they use different connection endpoints, plugins and authorization credentials. Please review our documentation to find out the details of each method.
> 
> In addition to that, please note that SNAPSHOT versions should not be used to sync with Maven Central (for more detail on this please review our FAQ). If you wish for your artifacts to be available from Maven Central, you will have to publish a release version. Snapshots are supported in legacy OSSRH.
> 
> Publishing through Gradle is also not yet officially supported in Central Portal, as Portal is still in early-access. There are however several community plugins for gradle that might be of interest if you wish to use Gradle. Publishing through maven via our Central Publishing Maven Plugin is fully supported.
> 
> If you are interested to publish from Central Portal, we must first revoke your deployment access from OSSRH before you can verify your namespace at https://central.sonatype.com/. 
>  
> Please let us know if you have any questions.
> 
> Thank you,
> The Central Team

**Comment by david-allison** [comment]
Info dump:

**Links**
* https://vanniktech.github.io/gradle-maven-publish-plugin/central/#secrets
* https://github.com/ankidroid/Anki-Android-Backend/settings/secrets/actions

We have 3 secrets:

* `SIGNING_PASSWORD`
* `SIGNING_PRIVATE_KEY`
* `SONATYPE_NEXUS_PASSWORD`


These are used as follows:

https://github.com/ankidroid/Anki-Android-Backend/blob/bc9db9a4678076cf5ef9fc7ef8c65e0143b619f7/.github/workflows/build-release.yml#L103-L117

**Comment by david-allison** [comment]
FUTURE

I now have a **new** **username** and **password** for Maven Central

This is known as a **User Token** by Maven Central

I will add the following secrets:

* `MAVEN_CENTRAL_USERNAME`
* `MAVEN_CENTRAL_PASSWORD`

I will update our CI to use these
