### ISSUE TITLE
Implement CI: Artifact publishing

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#5]
This will require a little thought (and likely manual work initially):

* Versioning (alpha|beta|stable)
* Publishing both `rsdroid` and `rsdroid-testing`  at the same version number

**Comment by david-allison-1** [comment]
Publishing now works via

* https://github.com/david-allison-1/Anki-Android-Backend/blob/rust-wip/.github/workflows/publish_testing.yml ([permalink](https://github.com/david-allison-1/Anki-Android-Backend/blob/23cfaffaf92edb0ee5c918fa312463be2b245763/.github/workflows/publish_testing.yml))
* https://github.com/david-allison-1/Anki-Android-Backend/blob/rust-wip/.github/workflows/publish_library.yml  ([permalink](https://github.com/david-allison-1/Anki-Android-Backend/blob/23cfaffaf92edb0ee5c918fa312463be2b245763/.github/workflows/publish_library.yml))

**Comment by mikehardy** [comment]
Related #33 #199 #200

**Comment by mikehardy** [comment]
I don't think so, #33 is the only real item left
