### ISSUE TITLE
Improve Docker script: check docker can run

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android-Backend#99]
Use `docker ps` to see if docker can run

It may return:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

`docker -v` works in this situation

**Comment by TarekkMA** [comment]
We can also use `docker version` it will return both cli version and the engine version

**Comment by david-allison-1** [comment]
> We can also use `docker version` it will return both cli version and the engine version

That's better - yep
